import {StyleProp, ViewStyle} from 'react-native';

export interface IconProps extends SvgProps {
  onPress?: () => void;
  disabled?: boolean;
  checked?: boolean;
  containerStyle?: StyleProp<ViewStyle>;
}

export interface SvgProps {
  name?: IconsList;
  size?: number;
  color?: string;
  style?: ViewStyle;
}

export type IconsList =
  | 'dashboard-outline'
  | 'chart-outline'
  | 'transfer-outline'
  | 'wallet-outline'
  | 'ecomining'
  | 'ecomining-filled'
  | 'user-outline'
  | 'dashboard'
  | 'chart'
  | 'transfer'
  | 'wallet'
  | 'user'
  | 'arrow-down'
  | 'arrow-up'
  | 'arrow-left'
  | 'arrow-right'
  | 'logo'
  | 'facebook'
  | 'google'
  | 'apple'
  | 'close'
  | 'close-small'
  | 'search'
  | 'check'
  | 'shield'
  | 'bell'
  | 'news'
  | 'settings'
  | 'headphones'
  | 'crown'
  | 'copy'
  | 'lock'
  | 'devices'
  | 'monitors'
  | 'alert'
  | 'big-warning-icon'
  | 'questionmark'
  | 'comment'
  | 'usd'
  | 'eur'
  | 'pencil'
  | 'tether'
  | 'ripple'
  | 'bitcoin'
  | 'litecoin'
  | 'ethereum'
  | 'put-in'
  | 'put-out'
  | 'eye'
  | 'eye-closed'
  | 'credit-card'
  | 'logout'
  | 'box'
  | 'qr-scanner'
  | 'trade-arrow'
  | 'info'
  | '_blank'
  | 'no-network'
  | 'login'
  | 'login-outline'
  | 'error'
  | 'quatum'
  | 'success'
  | 'plus'
  | 'idcard'
  | 'passport'
  | 'drivers'
  | 'stop'
  | 'play'
  | 'refresh'
  | 'id_card'
  | 'file'
  | 'minus'
  | 'dots'
  | 'chart-vertical'
  | 'chart-screen'
  | 'account-type'
  | 'fees'
  | 'history'
  | 'checkbox'
  | 'hands'
  | 'disable-2fa';
